### ISSUE TITLE
多个committer代码规范不统一

### ISSUE THREAD

**Issue by pingguoilove** [YunaiV/yudao-cloud#10]
首先感谢作者，这是一个非常好的springboot综合项目实例,能从工程中学到springboot，dubbo，微服务的知识。[应用分层](http://www.iocoder.cn/Onemall/Application-layer/?vip&onemall)这篇文章中讲到项目结构的时候，讲到service层和controller层的入参都是DTO，但是实际代码中出现了PO的概念，例如[UserAddressAddPO](https://github.com/YunaiV/onemall/blob/master/user/user-application/src/main/java/cn/iocoder/mall/user/application/po/UserAddressAddPO.java),在这里，应该和DTO是一个意思，建议统一一下

**Comment by YunaiV** [comment]
噢。理解你的意思。

因为早期的时候，没定完规范，所以出现这个情况。
后续，我们会逐步改掉。感谢提出。

欢迎来 pr ，一起改掉。

**Comment by YunaiV** [comment]
已经调整。
