### ISSUE TITLE
并发新增角色时角色名称重复问题

### ISSUE THREAD

**Issue by wuyiccc** [YunaiV/yudao-cloud#100]
碰到问题，请在 <https://github.com/YunaiV/yudao-cloud/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息
您好，请问在代码里面新增角色的时候，我看sql里面没有对system_role表字段的name加唯一性约束, 然后代码里面进行查询校验的时候也没有加锁之类的处理，这块是否会产生并发新增角色，角色名称重复的问题啊，还是说在其他地方解决了这个问题？

- yudaocloud 版本：master分支
- 操作系统：macos
- 数据库：mysql8.0.12

### 你猜测可能的原因
并发新增角色导致角色名称重复

### 相关代码

![image](https://github.com/YunaiV/yudao-cloud/assets/56572026/0ebc3305-0084-47c2-9e77-1f9d0aeaf8ce)

![image](https://github.com/YunaiV/yudao-cloud/assets/56572026/63763996-b0b0-4437-8022-fdb95731d3af)

**Comment by YunaiV** [comment]
可以通过唯一索引哈。

不过角色名本身不是一个很强要求的判重，所以暂时不想增加这块的复杂性。
