### ISSUE TITLE
【欢迎贡献】希望登录安全性优化

### ISSUE THREAD

**Issue by CV-Devlau** [YunaiV/yudao-cloud#102]
希望增加登录的一些安全性功能，并且提高暴力破解成本。例如：
1. 用户名密码通过RSA加密传输（用在没有https的情况或对系统有安全要求时一般不让明文传输）
2. 登录失败多次后锁定账户(锁用户/IP)，日志记录，解锁
3. 手机验证码防刷（手机号、ip）
4. oauth2密码模式同2，恶意的第三方申请拿到一对客户端id和密钥后也能暴力破解出所有用户密码

**Comment by YunaiV** [comment]
不错的建议，有兴趣可以 PR 贡献哈。

看着都是中等难度的。

**Comment by wyyl1** [comment]
## 其他思路

- 登录用户向系统发送验证码：可以避免刷验证码（12306 注册现在已采用）
- 通过[Google 身份验证器]进行登录

**Comment by YunaiV** [comment]
由于暂时没人贡献，且本身不算高优需求，暂时关闭。
