### ISSUE TITLE
模块开启部门、用户权限后，增加的时候是否需要单独编写代码赋值dept_id和user_id，有没有别的实现方式，能否提供一个开启部门、用户权限全过程的示例或说明文档

### ISSUE THREAD

**Issue by 13011891948** [YunaiV/yudao-cloud#106]

**Comment by YunaiV** [comment]
阅读 https://cloud.iocoder.cn/data-permission/ 以及对应视频哈。

**Comment by 13011891948** [comment]
你没理解我的意思

查询已经没问题了，配置都配好了

新增数据的时候有问题，dept_id为空

这个dept_id是否只能使用最笨的方法，根据当前登录人获取部门id，然后赋值给实体，传递到后端保存？？？

还是说有更高级、更方便的方式添加
