### ISSUE TITLE
【欢迎贡献】导出Excel:Long类型ID会丢失精度

### ISSUE THREAD

**Issue by iliyaohui** [YunaiV/yudao-cloud#109]
碰到问题，请在 <https://github.com/YunaiV/yudao-cloud/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：
- 操作系统：
- 数据库：

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：xxxxxx

### 复现步骤

第一步，

第二步，

第三步，

### 报错信息

带上必要的截图

**Comment by iliyaohui** [comment]
<img width="306" alt="image" src="https://github.com/YunaiV/yudao-cloud/assets/39508319/6516e995-ec36-447e-a874-500c0a901183">
<img width="545" alt="image" src="https://github.com/YunaiV/yudao-cloud/assets/39508319/4f301a75-aebc-4e92-a417-e90ee99aef3f">

**Comment by iliyaohui** [comment]
<img width="1680" alt="image" src="https://github.com/YunaiV/yudao-cloud/assets/39508319/55c0d630-5ec1-4b4d-897a-c43999ced3a2">

**Comment by iliyaohui** [comment]
<img width="754" alt="image" src="https://github.com/YunaiV/yudao-cloud/assets/39508319/b7c173bc-9e2e-4d7d-b21b-faa95a93018e">
package cn.eteahouse.cloud.framework.excel.core.convert;

import com.alibaba.excel.converters.Converter;
import com.alibaba.excel.enums.CellDataTypeEnum;
import com.alibaba.excel.metadata.GlobalConfiguration;
import com.alibaba.excel.metadata.data.WriteCellData;
import com.alibaba.excel.metadata.property.ExcelContentProperty;

public class LongConvert implements Converter<Long> {
    @Override
    public Class<?> supportJavaTypeKey() {
        throw new UnsupportedOperationException("暂不支持，也不需要");
    }

    @Override
    public CellDataTypeEnum supportExcelTypeKey() {
        throw new UnsupportedOperationException("暂不支持，也不需要");
    }

    @Override
    public WriteCellData<?> convertToExcelData(Long value, ExcelContentProperty contentProperty,
                                               GlobalConfiguration globalConfiguration) throws Exception {
        return new WriteCellData<>(value.toString());
    }
}

**Comment by iliyaohui** [comment]
加个转换类

**Comment by YunaiV** [comment]
不错的建议。要不参考 https://blog.csdn.net/qq_36069670/article/details/123507202 pr 下？
选用方案二

这个应该做成全局的。

**Comment by YunaiV** [comment]
已修复。
