### ISSUE TITLE
数据权限控制哪里，我分别建立了两个账号，建立了2个角色 一个角色属于开发部 一个属于运维部 然后给他们相同的菜单权限，他们分别建立数据，但是我登录这两个账号，按理说他们只能看到本部门的数据但是他们看到确是全部的数据，数据权限这一块需要怎么配置吗 是我配置不对还是这地方就没有做

### ISSUE THREAD

**Issue by gsdong** [YunaiV/yudao-cloud#110]
碰到问题，请在 <https://github.com/YunaiV/yudao-cloud/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：
- 操作系统：
- 数据库：

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：xxxxxx

### 复现步骤

第一步，

第二步，

第三步，

### 报错信息

带上必要的截图

**Comment by YunaiV** [comment]
https://cloud.iocoder.cn/data-permission/

看下文档哈。
