### ISSUE TITLE
分页查询接口ReqVO里面的字段，全部丢失字段值

### ISSUE THREAD

**Issue by dingziyang** [YunaiV/yudao-cloud#113]
### 基本信息

- ruoyi-vue-pro 版本：tag1.8
- 操作系统：MacOs Catalina
- 数据库：Mysql 8.0.33

### 你猜测可能的原因

猜测可能是yudao框架反序列化配置不对

### 复现步骤

第一步，找到一个符合此问题描述的接口，比如yudao-module-system模块的DictTypeController的pageDictTypes接口

第二步，本地运行yudao-module-system，在**swagger界面**上，手动输入很多查询参数，调用DictTypeController的pageDictTypes接口，发现查询参数都没生效

第三步，在DictTypeController的pageDictTypes接口debug，发现入参 (DictTypePageReqVO对象) 里面的字段值全部丢失

### 报错信息

无报错信息，就是查询条件不生效。

**Comment by xjg2012** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，邮件已经收到，我将尽快给您回复。

**Comment by dingziyang** [comment]
换了postman，发现是可以的。说明接口没问题，是knife4j界面解析问题
