### ISSUE TITLE
mysql schema init missing pay_channel

### ISSUE THREAD

**Issue by xiaoyao9184** [YunaiV/yudao-cloud#115]
### 基本信息

- ruoyi-vue-pro 版本：77e98bb
- 操作系统：
- 数据库：

mysql schema init脚本丢失pay_channel表，
对比 pgsql 是有的

https://github.com/YunaiV/yudao-cloud/blob/master/sql/postgresql/ruoyi-vue-pro.sql#L1965-L1965

**Comment by YunaiV** [comment]
https://cloud.iocoder.cn/pay/build/
