### ISSUE TITLE
启动  MpServerApplication  模块报错，Error creating bean with name 'wxMaService' defined in。。。

### ISSUE THREAD

**Issue by autumn11** [YunaiV/yudao-cloud#116]
碰到问题，请在 <https://github.com/YunaiV/yudao-cloud/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- yudao-cloud 版本：1.8.3-snapshot
- 操作系统：macOs
- 数据库：mysql5.7

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：可能是配置的原因

### 复现步骤

第一步，启动  MpServerApplication  模块报错

### 报错信息
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'wxMaService' defined in class path resource [com/binarywang/spring/starter/wxjava/miniapp/config/WxMaServiceAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [cn.binarywang.wx.miniapp.api.WxMaService]: Factory method 'wxMaService' threw exception; nested exception is java.lang.NullPointerException: null key in entry: null={"accessTokenLock":{"sync":{"state":0}},"expiresTime":0,"httpProxyPort":0,"retrySleepMillis":1000,"maxRetryTimes":5,"jsapiTicketExpiresTime":0,"cardApiTicketExpiresTime":0,"jsapiTicketLock":{"sync":{"state":0}},"cardApiTicketLock":{"sync":{"state":0}}}

带上必要的截图
<img width="467" alt="image" src="https://github.com/YunaiV/yudao-cloud/assets/3039629/e0dac305-181f-4aa3-9a36-eb2b621006db">

**Comment by autumn11** [comment]
更新代码后就好了，其实就是加了配置：

**Comment by YunaiV** [comment]
已经修复。
