### ISSUE TITLE
请问有没有升级到Spring6（SpringBoot3 + Spring Cloud Alibaba 2022.x）的打算？

### ISSUE THREAD

**Issue by Camio1945** [YunaiV/yudao-cloud#117]
不是Issue，就是打听一下。
如题：请问有没有升级到Spring6（SpringBoot3 + Spring Cloud Alibaba 2022.x）的打算？

**Comment by YunaiV** [comment]
关注 https://gitee.com/zhijiantianya/yudao-cloud/tree/master-boot3/ 分支
