### ISSUE TITLE
代码生成器模板与mybatis-plus模版差异

### ISSUE THREAD

**Issue by arvin-xiao** [YunaiV/yudao-cloud#119]
碰到问题，请在 <https://github.com/YunaiV/yudao-cloud/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：
- 操作系统：Windows
- 数据库：5.7

### 你猜测可能的原因

我花费了1小时自查
代码生成中集成了mybatisPlus和mybatisPlusJoin,模版service未继承IService与ServiceImpl，有什么特殊操作么，目前个人改造了模板，
暂未发现不兼容问题。只是有一点小疑问

### 复现步骤

第一步，

第二步，

第三步，

### 报错信息

带上必要的截图

**Comment by YunaiV** [comment]
Service 要收敛操作，MyBatis Plus 提供的 IService 接口过于宽泛，这样导致实在项目落地时，直接就破坏了分层结构。

很多同学直接拿 IService 去查询和操作 db。
