### ISSUE TITLE
首次启动系统登录报错后端报错502

### ISSUE THREAD

**Issue by zhang-weizhen** [YunaiV/yudao-cloud#125]
碰到问题，请在 <https://github.com/YunaiV/yudao-cloud/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：master
- 操作系统：mac
- 数据库：mysql8
本地docker 部署的nacos。redis , mysql
### 你猜测可能的原因

我花费了 2-4 小时自查，发现可能的原因是：网关转发时找不到对应的接口, 前端登陆图片时可以正常显示的,说明转发是能找到system服务的,但是在tencent的TenantFrameworkServiceImpl类里面去查询校验是否合法的时候发现调用不到http://system-server/rpc-api/system/tenant/valid?id=1

### 复现步骤

第一步，正常启动

第二步，输入账号密码验证通过

第三步，出现报错

### 报错信息
<img width="1339" alt="截屏2023-12-20 17 15 03" src="https://github.com/YunaiV/yudao-cloud/assets/19775402/68200111-c4e5-4293-ba23-d683755a02a1">

**Comment by YunaiV** [comment]
暂时没碰到，建议自查下哈。
