### ISSUE TITLE
能提供promotion_diy_template表的测试数据吗

### ISSUE THREAD

**Issue by 1533271091** [YunaiV/yudao-cloud#132]
碰到问题，请在 <https://github.com/YunaiV/yudao-cloud/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：2.0.1-jdk8-snapshot
- 操作系统：win10
- 数据库：mysql

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：promotion_diy_template表的缺少数据

### 复现步骤

第一步，本地用Hbuilder启动app（用浏览器运行）

第二步，执行静态文件下的初始化sql语句，本地启动后台服务

第三步，浏览器出现下方截图问题

### 报错信息

![image](https://github.com/YunaiV/yudao-cloud/assets/92710200/870f07a5-8ef2-47fa-b650-ae8a6a96a922)

**Comment by YunaiV** [comment]
参考 https://doc.iocoder.cn/mall/build/ 操作

**Comment by awaken-intellect** [comment]
上面的解决没？帮帮我
