### ISSUE TITLE
ErrorCodeConstants 类 错误码重复

### ISSUE THREAD

**Issue by Adrunkdoggy** [YunaiV/yudao-cloud#137]
### 基本信息

- ruoyi-vue-pro 版本：v2.0.1
- 操作系统：win
- 数据库：mysql

### 你猜测可能的原因
ErrorCodeConstants 类 错误码重复

### 报错信息

![image](https://github.com/YunaiV/yudao-cloud/assets/104116030/383ea817-e619-41e3-8228-f611c18dbdd2)

**Comment by YunaiV** [comment]
已修复~
