### ISSUE TITLE
infra-server无法启用Spring Boot Admin服务端的Server服务

### ISSUE THREAD

**Issue by RootFive** [YunaiV/yudao-cloud#139]
### 基本信息

- yudao-cloud 版本：2.0.1（分支master-jdk21）
- 操作系统：windows 11
- 数据库：8.0

### infra-server无法启用Spring Boot Admin服务端的Server服务
我尝试了IDEA和Eclipse两种IDE编辑器，都无法配置启用yudao-module-infra模块下yudao-module-infra-biz中的Spring Boot Admin Server 服务端，不管是网关访问还是直接访问都会报500错误：

### 复现步骤

第一步，更改配置

第二步，启动yudao-module-infra-biz服务

第三步，页面访问，查看页面和后台空置台报错信息

### 报错信息
页面访问：
![image](https://github.com/YunaiV/yudao-cloud/assets/22868106/52658c66-2f97-49c2-8c2f-3b5455872f7f)

后端空置台报错：
![企业微信截图_17116807237879](https://github.com/YunaiV/yudao-cloud/assets/22868106/521a3a41-8889-488c-bf0b-31dc418b7f91)

**Comment by YunaiV** [comment]
https://cloud.iocoder.cn/server-monitor/#_1-1-%E9%85%8D%E7%BD%AE
