### ISSUE TITLE
艿艿 seata的实战在哪里呀 找不到

### ISSUE THREAD

**Issue by liuyi9608** [YunaiV/yudao-cloud#14]

**Comment by chaoxihailing** [comment]
这个直接下载最高版本服务端 0.8，解压后，进入目录下启动服务，如下图
![image](https://user-images.githubusercontent.com/17508916/64922894-d7985980-d806-11e9-9cac-57c9e0ba97b5.png)


客户端使用配套的版本 0.8
<seata.version>0.8.0</seata.version>

<dependency>
    <groupId>io.seata</groupId>
    <artifactId>seata-all</artifactId>
    <version>${seata.version}</version>
</dependency>
