### ISSUE TITLE
【欢迎认领任务】只能发送未修改过有效期类型的优惠券

### ISSUE THREAD

**Issue by baukasten-c** [YunaiV/yudao-cloud#142]
### 基本信息

-  版本：yudao-cloud

### 复现步骤

第一步，发现“发送优惠券”列表中总是少数据

第二步，手动修改日期后，数据出现

第三步，查看代码，发现忽略一种情况：最初为固定日期，后改为领取之后。这样的优惠券有过期的 ValidEndTime，但是应该算作未过期

### 报错信息

![image](https://github.com/YunaiV/yudao-cloud/assets/94286327/c2ccf487-c253-4fd7-acf8-7c7d3f2df711)

![image](https://github.com/YunaiV/yudao-cloud/assets/94286327/5b4dbfb1-8758-4262-8ae4-4221fe6d391c)

![image](https://github.com/YunaiV/yudao-cloud/assets/94286327/4c6234fe-91b3-4f82-ab8e-960171f35970)

**Comment by xjg2012** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，邮件已经收到，我将尽快给您回复。

**Comment by YunaiV** [comment]
已修复
