### ISSUE TITLE
Feign调用 不验证用户  怎么做啊  现在有的接口微服务调用会报： 账号未登录

### ISSUE THREAD

**Issue by lexang** [YunaiV/yudao-cloud#147]
Feign调用 不验证用户  怎么做啊  现在有的接口微服务调用会报： 账号未登录

**Comment by Tomoko-hjf** [comment]
@lexang 请问这个该如何解决呢，谢谢~

**Comment by Skylark-hjyp** [comment]
@lexang 突然看到这个问题，我的场景是外部第三方系统调用我的接口服务A，服务A再去调用服务B。

因为实际使用中外部服务不需要登录就可以调用服务A，所以做了两步：
* 1. 首先放开服务A的访问权限；
* 2. 在服务A调用服务B之前，加上一个用户信息；

代码如下：
```java
@PostMapping("/report")
@Parameter(name = "alarmInfoReportVO", description = "报警信息VO对象", required = true)
@PermitAll  // 放开访问权限，使第三方系统可以调用此接口
public CommonResult<String> reportAlarmInfo(@Valid @RequestBody AlarmInfoReportVO alarmInfoReportVO, HttpServletRequest request) {
    try {
        //     添加用户信息   
        LoginUser loginUser = new LoginUser();
        loginUser.setId(90000002024L);
        loginUser.setUserType(UserTypeEnum.ADMIN.getValue());
        SecurityFrameworkUtils.setLoginUser(loginUser, request);
        alarmInfoReportVO.setReportType(AlarmConstant.ReportType.PUSH);
        return success(alarmInfoService.reportAlarmInfo(alarmInfoReportVO));
    } catch (Exception e) {
        log.error("提交报警处理方案时出现异常，具体异常为： {}", e.getMessage());
        e.printStackTrace();
        throw e;
    }
}
```

时间太长，可能你已经解决了，但还是希望有帮助！

**Comment by YunaiV** [comment]
> @lexang 突然看到这个问题，我的场景是外部第三方系统调用我的接口服务A，服务A再去调用服务B。
> 
> 因为实际使用中外部服务不需要登录就可以调用服务A，所以做了两步：
> 
> * 1. 首先放开服务A的访问权限；
> * 2. 在服务A调用服务B之前，加上一个用户信息；
> 
> 代码如下：
> 
> ```java
> @PostMapping("/report")
> @Parameter(name = "alarmInfoReportVO", description = "报警信息VO对象", required = true)
> @PermitAll  // 放开访问权限，使第三方系统可以调用此接口
> public CommonResult<String> reportAlarmInfo(@Valid @RequestBody AlarmInfoReportVO alarmInfoReportVO, HttpServletRequest request) {
>     try {
>         //     添加用户信息   
>         LoginUser loginUser = new LoginUser();
>         loginUser.setId(90000002024L);
>         loginUser.setUserType(UserTypeEnum.ADMIN.getValue());
>         SecurityFrameworkUtils.setLoginUser(loginUser, request);
>         alarmInfoReportVO.setReportType(AlarmConstant.ReportType.PUSH);
>         return success(alarmInfoService.reportAlarmInfo(alarmInfoReportVO));
>     } catch (Exception e) {
>         log.error("提交报警处理方案时出现异常，具体异常为： {}", e.getMessage());
>         e.printStackTrace();
>         throw e;
>     }
> }
> ```
> 
> 时间太长，可能你已经解决了，但还是希望有帮助！

默认 rpc api 可以配置不需要登录访问。

因为 rpc 是否要登录，更多还是逻辑层面去决定哈。
