### ISSUE TITLE
VO中的@Accessors(chain = true) @EqualsAndHashCode(callSuper = true) 报错

### ISSUE THREAD

**Issue by whitex8023** [YunaiV/yudao-cloud#150]
碰到问题，请在 <https://github.com/YunaiV/yudao-cloud/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：4.0.0
- 操作系统：windows
- 数据库：mysql

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：lombok注解问题

### 复现步骤

第一步，引入项目

第二步，build项目(maven-install)

第三步，

### 报错信息

带上必要的截图
![image](https://github.com/YunaiV/yudao-cloud/assets/39975976/dc967289-78dd-430d-bf34-75b9d93d3fa4)

**Comment by YunaiV** [comment]
建议使用 idea 哈。
