### ISSUE TITLE
BPM 工作流专区-流程定义规则分配部分

### ISSUE THREAD

**Issue by 48038411** [YunaiV/yudao-cloud#160]
碰到问题，请在 <https://github.com/YunaiV/yudao-cloud/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：2.1.0
- 操作系统：Windows11
- 数据库：MySQL

### 你猜测可能的原因
【重构】审批人的分配规则实现，移除 bpm_task_assign_rule 表，使用 bpmn UserTask 自定义属性存储
我目前在参考yudao-cloud这个项目实现BPM工作流，在参考演示网站实现大部分之后发现部署流程时提示未配置审批人，我在xml文件里自定义添加属性会报错 org.flowable.bpmn.exceptions.XMLException: Error reading XML  在演示网站看到返回的xml文件和规则分配是分开的，规则分配的接口在代码里找不到，请问是付费的模块吗

### 复现步骤

第一步，

第二步，

第三步，

### 报错信息

带上必要的截图

**Comment by YunaiV** [comment]
不是噢。演示网站没部署最新的代码，是老的。

新的都融合到 bpmn 的 xml 里了，更加符合规范

**Comment by 48038411** [comment]
> 不是噢。演示网站没部署最新的代码，是老的。
> 
> 新的都融合到 bpmn 的 xml 里了，更加符合规范

好的，谢谢。期待您新的版本
