### ISSUE TITLE
BPM工作流模块表单组件编号和id无法自定义

### ISSUE THREAD

**Issue by heyaonan** [YunaiV/yudao-cloud#161]
### 基本信息
- ruoyi-vue-pro 版本：[master-jdk17](https://github.com/YunaiV/ruoyi-vue-pro/tree/master-jdk17)
- 操作系统：windows10
- 数据库：postgres

### 你猜测可能的原因

我花费了 2-4 小时自查，发现可能的原因是：目前版本不支持表单组件编号自定义

### 复现步骤

![image](https://github.com/YunaiV/yudao-cloud/assets/17605927/184413ed-40dc-4c1e-92b3-24230976350e)

**Comment by heyaonan** [comment]
因为我是调用创建流程实例的接口来发起流程，需要将表单的变量值传入创建流程实例接口，但是现在表单里的组件id不是自定义，无法根据业务实体的字段来设置变量值。

**Comment by YunaiV** [comment]
收到，这个可以看下 form-create 设计器的文档

我们也研究下。

**Comment by YunaiV** [comment]
我看了下，貌似可以编辑的呀

https://view.form-create.com/custom-field
