### ISSUE TITLE
开发环境停止服务端口依然占用

### ISSUE THREAD

**Issue by Jonneykang** [YunaiV/yudao-cloud#163]
基本信息
- ruoyi-vue-pro 版本：2.1.0-jdk8-snapshot
- 操作系统：windows11
- 数据库：mysql5.7
- IDEA: IntelliJ IDEA Community Edition 2024.1.4

问题
IDEA启动两必要服务：“yudao-module-system”和“yudao-module-infra”，重启后tomcat端口本地一直被上次启动jar服务占用，需要手动kill掉对应的进程，这是什么原因导致的，是不是跟开启 SpringBoot 自动配置有关呢？

上图：
![20240720155403](https://github.com/user-attachments/assets/42fa6d8e-9181-43bb-990e-0627b56d906b)

**Comment by YunaiV** [comment]
没关系，应该是你那关闭不对。。。
