### ISSUE TITLE
v2.2.0(jdk17/21) tag的的pom.xml文件还是jdk1.8的

### ISSUE THREAD

**Issue by bro0k** [YunaiV/yudao-cloud#166]
碰到问题，请在 <https://github.com/YunaiV/yudao-cloud/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：v2.2.0(jdk17/21)
- 操作系统：linux
- 数据库：mysql

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：pom.xml文件错误

### 复现步骤

第一步，

第二步，

第三步，

### 报错信息

带上必要的截图
![图片](https://github.com/user-attachments/assets/f34ab2fa-a4a3-49af-8077-e14ccbe4baa4)

**Comment by YunaiV** [comment]
手抖了。。。请使用 master-jdk17 噶。
