### ISSUE TITLE
关于其他服务服务实现BpmProcessInstanceStatusEventListener审批通过后无法正常走业务逻辑的问题

### ISSUE THREAD

**Issue by fangymzg** [YunaiV/yudao-cloud#168]
### 基本信息

- ruoyi-vue-pro 版本：2.1.0
- 操作系统：windows
- 数据库：mysql

### 你猜测可能的原因

由于BPM是一个单独的服务, 且没有依赖其他的业务服务, 所以导致SPRING在加载时候无法加载到其他服务的实现类,从而无法执行相应的业务代码

**Comment by YunaiV** [comment]
https://gitee.com/zhijiantianya/yudao-cloud/issues/I9H818

参考这个解决哈

**Comment by fangymzg** [comment]
> https://gitee.com/zhijiantianya/yudao-cloud/issues/I9H818
> 
> 参考这个解决哈

好吧, 这个方案我也想到了, 主要是想看看大佬有没有更好的解决方案
