### ISSUE TITLE
后台管理员的用户表信息，权限信息怎么都是空的

### ISSUE THREAD

**Issue by jgzl** [YunaiV/yudao-cloud#17]
https://github.com/YunaiV/onemall/blob/master/docs/sql/mall_admin.sql

**Comment by dlhf** [comment]
https://github.com/YunaiV/onemall/blob/9b913af9c6efa893827e5387bd970827edd8f69c/docs/sql/mall_admin.sql#L59

**Comment by zhenxianyimeng** [comment]
权限点都有的，权限和角色之间的关系， 用户和角色之间的关系要自己建一下

**Comment by YunaiV** [comment]
https://doc.iocoder.cn/resource-permission/
