### ISSUE TITLE
启动报错 A component required a bean of type 'org.springframework.security.crypto.password.PasswordEncoder' that could not be found.

### ISSUE THREAD

**Issue by zrbg153359** [YunaiV/yudao-cloud#174]
碰到问题，请在 <https://github.com/YunaiV/yudao-cloud/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：
- 操作系统：
- 数据库：

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：xxxxxx

### 复现步骤

第一步，

第二步，

第三步，

### 报错信息
Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-09-04 10:27:34.891 | ERROR 26904 | main [TID: N/A] o.s.b.d.LoggingFailureAnalysisReporter   | 

***************************
APPLICATION FAILED TO START
***************************

Description:

A component required a bean of type 'org.springframework.security.crypto.password.PasswordEncoder' that could not be found.

Action:

Consider defining a bean of type 'org.springframework.security.crypto.password.PasswordEncoder' in your configuration.

带上必要的截图
![image](https://github.com/user-attachments/assets/2be62abc-773c-4c80-8fbe-54da3719eb97)

![image](https://github.com/user-attachments/assets/cf153c3e-689c-493f-9ad7-f40659307788)

**Comment by glshi** [comment]
遇到同样的问题，请问是怎么解决的？
