### ISSUE TITLE
yudao-cloud release版本

### ISSUE THREAD

**Issue by zerozayu** [YunaiV/yudao-cloud#176]
碰到问题，请在 <https://github.com/YunaiV/yudao-cloud/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-cloud 版本：2.2.0
- 操作系统：windows10
- 数据库：mysql

### 你猜测可能的原因

目前release中jdk17的包下载后还是jdk8的相关貌似，pom文件中的jdk版本还是jdk8，但是分支中版本已经是jdk17了

### 复现步骤

第一步，

第二步，

第三步，

### 报错信息

带上必要的截图

**Comment by YunaiV** [comment]
恩恩。= = 我发布错了。

预计月底会发最新的。
