### ISSUE TITLE
admin-web启动不成功

### ISSUE THREAD

**Issue by chaoxihailing** [YunaiV/yudao-cloud#18]
环境 node v10.15.2 npm v6.11.3
执行的操作
![image](https://user-images.githubusercontent.com/17508916/64922948-555c6500-d807-11e9-936d-70baeb0891b3.png)

错误日志，
![image](https://user-images.githubusercontent.com/17508916/64922924-2f36c500-d807-11e9-8c7b-7a3c1562492c.png)

**Comment by YunaiV** [comment]
https://cloud.iocoder.cn/quick-start/
