### ISSUE TITLE
商城微信小程序端，点击微信图标进行登录报错

### ISSUE THREAD

**Issue by Buywatermelon** [YunaiV/yudao-cloud#183]
碰到问题，请在 <https://github.com/YunaiV/yudao-cloud/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：master
- 操作系统：微信小程序
- 数据库：MySQL

### 你猜测可能的原因
![image](https://github.com/user-attachments/assets/7214d2d9-8b9b-481e-ae57-b6b884a86174)

![image](https://github.com/user-attachments/assets/1a85471b-eda3-4d1e-a85c-9eb93240713d)
使用微信小程序登录第一次登录，并没有`username`参数，在插入登录日志时，对`LoginLogCreateReqDTO`对象的`username`参数进行了`@NotBlank`校验，导致第一次登录报错。

![image](https://github.com/user-attachments/assets/f2f5b20f-3a8e-445e-96d5-caef6fb904e4)
登录失败后，第二次点击登录，由于第一次登录调用`system`远程接口成功返回`socialUser`，在`system_social_user_bind`表中成功创建记录并没有因为第一次登录的校验失败回滚回去，从而导致之后的登录存在`socialUser`，但不存在`user`。
![image](https://github.com/user-attachments/assets/ef29d9fe-49c7-4198-a3a9-1daa152836a3)

建议修改的方式：
使用`@Validation`的`group`对登录日志的接口进行分组校验，对于不同的登录场景创建不同的组接口。
这样即可以对`LoginLogCreateReqDTO`对象进行合理的校验，又可以根据不同的业务场景进行校验的区分。

（必填）我花费了 2-4 小时自查，发现可能的原因是：xxxxxx

### 复现步骤

第一步，

第二步，

第三步，

### 报错信息

带上必要的截图

**Comment by YunaiV** [comment]
已修复。

https://gitee.com/zhijiantianya/yudao-cloud/commit/a887c364f97b1f8a4efca116045d05e62c6fc62b

boot 已经改了，少同步到 cloud 了。
