### ISSUE TITLE
关于将rocketmq-spring-boot-starter依赖包升级为2.3.1后对应的rocketmq版本未升级问题

### ISSUE THREAD

**Issue by fangymzg** [YunaiV/yudao-cloud#185]
碰到问题，请在 <https://github.com/YunaiV/yudao-cloud/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：master
- 操作系统：微信小程序
- 数据库：mysql

### 你猜测可能的原因

能力有限, 未能发现问题

### 复现步骤

将stone-dependencies里面的 
<rocketmq-spring.version>2.2.3</rocketmq-spring.version> 升级为<rocketmq-spring.version>2.3.1</rocketmq-spring.version>
可以看到2.3.1里面依赖的rocketmq版本为 5.3.0
![PixPin_2024-10-15_16-29-42](https://github.com/user-attachments/assets/3b4c37bf-5733-4827-bed9-f38ba73df9f4)
但是当我打开依赖管理查看的时候发现依赖的包依旧为 4.9.4,我很确定我其他地方没有引用这个包(全局搜索过了)
但是当我新开一个项目并引入对应的包的时候, 发现又是对的 以下为新创建的项目和引入的包截图
![PixPin_2024-10-15_16-34-02](https://github.com/user-attachments/assets/84fb3fbb-fece-4354-b814-94abfb4e2f13)
![PixPin_2024-10-15_16-34-10](https://github.com/user-attachments/assets/02bddd01-1b78-402c-95bd-581bd623fe44)

**Comment by YunaiV** [comment]
https://mvnrepository.com/artifact/org.apache.rocketmq/rocketmq-v5-client-spring-boot-starter/2.3.1
