### ISSUE TITLE
ERP模块的数据权限BUG

### ISSUE THREAD

**Issue by BnjaLin** [YunaiV/yudao-cloud#190]
### 基本信息

创建了两个仅有个人数据权限的用户，在ERP模块中分别创建自己的客户和销售订单，发现还是可以看到另一个用户的客户和订单，这是一个BUG，正确的应该只能看到自己的客户和订单。而CRM模块中，这个功能是正常的。

- ruoyi-vue-pro 版本：最新版
- 操作系统：linux
- 数据库：mysql

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是： 表查询时没有按照用户的数据权限查询

**Comment by YunaiV** [comment]
crm 有单独的数据权限：https://cloud.iocoder.cn/data-permission/

erp 的数据权限，需要按需添加：https://cloud.iocoder.cn/data-permission/
