### ISSUE TITLE
关于nacos修改配置不能实时生效的问题

### ISSUE THREAD

**Issue by ZarfLan** [YunaiV/yudao-cloud#202]
大佬，我这边修改了nacos中的配置，不能实时生效，
必须重启系统，才能生效。
或者在@Value 或 @ConfigurationProperties的Bean同时加上@RefreshScope注解才能实时生效。

请问有什么方法，可以让全局配置实时生效呢，而不需要在每个Bean上加一个@RefreshScope注解

**Comment by YunaiV** [comment]
这个是 spring cloud 正常情况，可以多看下文档哈。
