### ISSUE TITLE
发现有好些todo,项目好久没有更新了，还会后续更新吗

### ISSUE THREAD

**Issue by Concentrate** [YunaiV/yudao-cloud#25]
读了这个项目后，这里发现一些问题，以供参考:

前端相关:
1. 增加品牌时候，不发出请求
2. 增加子种类的时候，点击上传图片就跳过.
3. Invalid Host header,这个问题,请求商城子项目,部署到云上时候
4. 发布商品时候,规格明细那里,产生数量和价格的条目数,应该是商品规格属性的排列组合,不能有重复,现在出现重复,前端页面生成数据bug
5. 优惠券,折扣卷那里,会崩

后端相关，主要是好一些todo还没做，看起来还是有些不完善，少量问题自己阅读时候发现:
todo 系列：
1. 下订单，没减库存
2. 订单过期逻辑还没有
3. 退货相关，重新入库的好像没加（不知道是不是需要手动入库比较合理，这样的考虑？）
4. 还有一些其他todo
5. 还有一个支付成功通知逻辑，代码注释写的是
 `定时任务，扫描 nextNotifyTime < lastExecuteTime 的任务`
感觉不用这个lastExecuteTime，加上感觉疑惑，是不是` nextNotifyTime < now()`时候就可以执行通知逻辑了

**Comment by YunaiV** [comment]
感谢~

应该 4 月或者 5 月，可能会开始更新。最近略微有点忙，自己又捉摸想做大的重构，所以一直就拖拖拉拉的。
