### ISSUE TITLE
master分支项目整体编译无法通过

### ISSUE THREAD

**Issue by noah-wung** [YunaiV/yudao-cloud#30]
1、很多模块的pom中依赖了system-sdk、user-sdk，但是项目已经没有这两个模块
2、各子项目中service-impl模块中的dataobject中的实体类集成的BaseDO或DeletableDO引入的还是cn.iocoder.common.framework.dataobject包下，这个类似乎已经已经移动到cn.iocoder.mall.mybatis.dataobject，导致很多模块都是编译报错的

**Comment by YunaiV** [comment]
https://cloud.iocoder.cn/quick-start/
可以拉下最新代码。
