### ISSUE TITLE
待确认修复的逻辑问题

### ISSUE THREAD

**Issue by wangrqsh** [YunaiV/yudao-cloud#31]
fork 的代码，梳理逻辑时，发现三个问题:
1：
AdminServiceImpl.java
updateAdmin()  方法
password参数未encodePassword存储,账号修改后无法登陆
2：
updateAdminStatus()
DISABLE 时会将当前用户token失效,应该是被更新的用户token失效,参数传错了
3：
AdminErrorCodeEnum.java
账号被禁用 与 账号已经存在  状态码相同

**Comment by YunaiV** [comment]
感谢提出。

最近在重构！

**Comment by YunaiV** [comment]
重构完成！
