### ISSUE TITLE
异步日志拦截器中-异步入库失效问题

### ISSUE THREAD

**Issue by airTisan** [YunaiV/yudao-cloud#37]
cn.iocoder.mall.web.core.interceptor.AccessLogInterceptor#afterCompletion调用同一个类中@async注解的addAccessLog方法，正确的方式是将需要异步的方法写在另外一个类中

**Comment by YunaiV** [comment]
收到，晚点我改改，谢谢~

**Comment by YunaiV** [comment]
已修复。
