### ISSUE TITLE
Manager 和 Services 层

### ISSUE THREAD

**Issue by maoqyhz** [YunaiV/yudao-cloud#47]
项目中的调用逻辑为：
controller -> rpc -> manager -> service -> dao(mapper)

根据阿里的工程结构以及[Onemall 电商开源项目 —— 应用分层](https://www.iocoder.cn/Onemall/Application-layer/)中提到的，
manager 和 service 是不是反了一下？

**Comment by YunaiV** [comment]
> 项目中的调用逻辑为： controller -> rpc -> manager -> service -> dao(mapper)
> 
> 根据阿里的工程结构以及[Onemall 电商开源项目 —— 应用分层](https://www.iocoder.cn/Onemall/Application-layer/)中提到的， manager 和 service 是不是反了一下？

命名不同，作用是相同的哈。如果采用 DDD：ApplicationService + DomainService ~
保证相同的作用就好，一个做逻辑的编排为主，一个提供单一领域的逻辑
