### ISSUE TITLE
艿艿 能提供下dubbo admin怎么配置的嘛

### ISSUE THREAD

**Issue by jilinwangyifei** [YunaiV/yudao-cloud#49]
艿艿好 dubbo admin 连接nacos配置文件怎么配置的啊 本地配置始终连不上

**Comment by YunaiV** [comment]
https://www.iocoder.cn/Dubbo/Admin/?self
我写过一篇，zk 的，嘿嘿

**Comment by YunaiV** [comment]
https://www.iocoder.cn/Dubbo/Admin/?self
我写过一篇，zk 的，嘿嘿
