### ISSUE TITLE
无token时如何进行的认证？

### ISSUE THREAD

**Issue by WuXiaoYang1** [YunaiV/yudao-cloud#64]
碰到问题，请在 <https://github.com/YunaiV/yudao-cloud/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- yudao-cloud 版本：1.6.2-snapshot
- 操作系统：windows
- 数据库：mysql

请问如果请求头不携带token请求时，是如何鉴权的，我看这两个filter里面，cn.iocoder.yudao.gateway.filter.security.TokenAuthenticationFilter，cn.iocoder.yudao.framework.security.core.filter.TokenAuthenticationFilter，如果没有token都是直接过了，那不相当于没有认证也可以调用接口了吗？

**Comment by LuGengYuan** [comment]
我实际接口请求测试无token是会提示我账号未登录，但是鉴权不知道在哪做的，望指教

**Comment by YunaiV** [comment]
可见 https://doc.iocoder.cn/resource-permission/ 文档
进一步讲解，可见 https://doc.iocoder.cn/video/ 视频
