### ISSUE TITLE
mybatis代码生成为什么不直接生成在项目路径里

### ISSUE THREAD

**Issue by jsl1992** [YunaiV/yudao-cloud#66]
这边mybatis实体生成，是生成一个文件夹。
这边还需要再复制一遍，为什么不直接生成在本地项目里对应的路径。

**Comment by jsl1992** [comment]
这个 每次都需要复制一遍觉得有点麻烦

**Comment by YunaiV** [comment]
可以自己实现一下哈；
我觉得直接写入容易覆盖，所以暂时不提供。
