### ISSUE TITLE
网关日志日志功能创建的LinkedHashMap对象没有指定初始长度，可以指定以提高性能

### ISSUE THREAD

**Issue by maclong1989** [YunaiV/yudao-cloud#69]
### 基本信息

- ruoyi-vue-pro 版本：4.0.0
- 操作系统：无
- 数据库：无

### 你猜测可能的原因

浏览代码时，发现网关日志日志打印时候用的是无默认大小初始化值的linkhashmap对象，而打印网关日志代码为固定在map中放置15个项目，所以可以在新建对象的时候指定初始化map中对象个数为15，以节省内存和提高性能。

### 复现步骤

![Uploading image.png…]()
AccessLogFilter.java
    private void writeAccessLog(AccessLog gatewayLog) {
        Map<String, Object> values = new LinkedHashMap<>(); // 手工拼接，保证排序
        values.put("userId", gatewayLog.getUserId());
        values.put("userType", gatewayLog.getUserType());
        values.put("routeId", gatewayLog.getRoute() != null ? gatewayLog.getRoute().getId() : null);
        values.put("schema", gatewayLog.getSchema());
        values.put("requestUrl", gatewayLog.getRequestUrl());
        values.put("queryParams", gatewayLog.getQueryParams().toSingleValueMap());
        values.put("requestBody", JsonUtils.isJson(gatewayLog.getRequestBody()) ? // 保证 body 的展示好看
                JSONUtil.parse(gatewayLog.getRequestBody()) : gatewayLog.getRequestBody());
        values.put("requestHeaders", JsonUtils.toJsonString(gatewayLog.getRequestHeaders().toSingleValueMap()));
        values.put("userIp", gatewayLog.getUserIp());
        values.put("responseBody", JsonUtils.isJson(gatewayLog.getResponseBody()) ? // 保证 body 的展示好看
                JSONUtil.parse(gatewayLog.getResponseBody()) : gatewayLog.getResponseBody());
        values.put("responseHeaders", gatewayLog.getResponseHeaders() != null ?
                JsonUtils.toJsonString(gatewayLog.getResponseHeaders().toSingleValueMap()) : null);
        values.put("httpStatus", gatewayLog.getHttpStatus());
        values.put("startTime", DateUtil.format(gatewayLog.getStartTime(), NORM_DATETIME_MS_FORMAT));
        values.put("endTime", DateUtil.format(gatewayLog.getEndTime(), NORM_DATETIME_MS_FORMAT));
        values.put("duration", gatewayLog.getDuration() != null ? gatewayLog.getDuration() + " ms" : null);
        log.info("[writeAccessLog][网关日志：{}]", JsonUtils.toJsonPrettyString(values));
}

**Comment by YunaiV** [comment]
可以 pr 一下

**Comment by YunaiV** [comment]
已优化
