### ISSUE TITLE
功能增加-不是bug

### ISSUE THREAD

**Issue by glide-the** [YunaiV/yudao-cloud#75]
碰到问题，请在 <https://github.com/YunaiV/yudao-cloud/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息
我在自己的项目中，实现了一个字段级别权限管理，这个项目中是否需要添加进来

相关设计
[知识库权限业务设计.pdf](https://github.com/YunaiV/yudao-cloud/files/9995588/default.pdf)

- ruoyi-vue-pro 版本：
- 操作系统：
- 数据库：

### 你猜测可能的原因

系统功能增加

### 复现步骤
 无
### 报错信息
 无

**Comment by YunaiV** [comment]
字段权限还在考虑，看了下整体设计没什么问题。

主要考虑，是不是有必要引入这样的特性，保持项目的简洁~
