### ISSUE TITLE
将配置放至Nacos后报错Unable to find instance for xxx

### ISSUE THREAD

**Issue by window1013** [YunaiV/yudao-cloud#79]
把applicaton-local.yaml里的配置移动到Nacos后，gateway就一直报Unable to find instance for xxx，无论是新创建的服务，还是自带的system、infra服务，请大家指导下哪里有错误或者缺少什么步骤

基本信息
ruoyi-vue-pro 版本：1.6.5
操作系统：CentOS 7
数据库：MySQL5.7
你猜测可能的原因
（必填）我花费了 2-4 小时自查，发现可能的原因是：未知

复现步骤
第一步，我新建的namespace，创建了 lighting-server配置(lighting-server是spring.application.name)，里面的配置是把application-local.yaml里的配置复制进来，和system服务的配置基本一样
![image](https://user-images.githubusercontent.com/12764827/215266067-53389b70-7117-4b21-9b81-f75d9d1aa9b6.png)

第二步，在bootstrap-local.yaml里修改namespace为创建的namesapce的id
![修改bootstrap-local.yaml里Nacos的namespace](https://user-images.githubusercontent.com/12764827/215266072-deb29229-9d14-40fe-a1a9-0c8c7b07183a.png)

第三步，把原来本地的application-local.yaml的内容清空掉

第四步，把脚本deploy.sh里的启动命令的--spring.profiles.active改为-Dspring.profiles.active
![image](https://user-images.githubusercontent.com/12764827/215266079-abdeaed9-7ae2-462d-904d-ae8a4bd21350.png)

第五步，gateway服务配置里的route加上lighting-server的配置
![image](https://user-images.githubusercontent.com/12764827/215266088-bc103437-9825-48ac-8407-99aabd29f095.png)

报错信息
Unable to find instance for lighting-server
![image](https://user-images.githubusercontent.com/12764827/215266093-06b4743b-276f-43f7-a585-4a4b9decb7b3.png)

**Comment by YunaiV** [comment]
暂时没有碰到过，可以参考 https://www.iocoder.cn/Spring-Cloud-Alibaba/Nacos-Config/ 文章，调试下自己的环境，先确认下 Nacos 配置是否成功加载。如果成功加载，再调试下 Nacos 注册中心，是否拉取到实例。
