### ISSUE TITLE
查询自己的站内信信息异常提示 “获取不到数据库的类型”

### ISSUE THREAD

**Issue by tangjiale** [YunaiV/yudao-cloud#80]
### 基本信息

- yudao-cloud版本：1.6.6-snapshot
- 操作系统：win11
- 数据库：mysql8.0

### 你猜测可能的原因

使用nacos配置中心，mybatis组件IdTypeEnvironmentPostProcessor比拉取配置中心先执行，获取不到 DbType,初始化 SQL 静态变量为空，在使用QueryWrapperX的limitN方法的时候 提示，Assert.notNull(SqlConstants.DB_TYPE, "获取不到数据库的类型");

### 复现步骤

第一步，
   使用nacos配置中心
第二步，
 点击个人的站内信按钮，报系统异常

### 报错信息

![image](https://user-images.githubusercontent.com/8148159/215683280-130335ee-420a-49f8-92f2-bfb41b87662b.png)

![image](https://user-images.githubusercontent.com/8148159/215683576-3d760585-1fcd-4cdc-9f12-bb0764d73595.png)

![image](https://user-images.githubusercontent.com/8148159/215683848-6a64c5b0-7b68-4bd5-9133-2cd3610c7571.png)

**Comment by YunaiV** [comment]
具体怎么配置的？
测试过，暂时没碰到这样的问题

**Comment by YunaiV** [comment]
已经是已修复的。
