### ISSUE TITLE
租户的请求未传递，请进行排查 

### ISSUE THREAD

**Issue by guobin510** [YunaiV/yudao-cloud#82]
碰到问题，请在 <https://github.com/YunaiV/yudao-cloud/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：1.6.6-snapshot
- 操作系统：win10
- 数据库：mysql

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：一直没有发现问题在哪里。断点调式了

我按文档新建了一个模块。新增了demo/test
![image](https://user-images.githubusercontent.com/10906487/222305003-26263ef2-7d6d-47e9-ad7c-73b5dbec37cd.png)
这里也添加了过滤
![image](https://user-images.githubusercontent.com/10906487/222305029-25fdbec1-a532-4f61-9e72-5ad8fcf8885f.png)
用postman通过网关请求也没有问题。但是后台却报一下错误
![image](https://user-images.githubusercontent.com/10906487/222305046-64b94071-4331-466c-8753-e4d5d1d1bdf6.png)
![image](https://user-images.githubusercontent.com/10906487/222305063-160cf2b6-8597-4ef6-b684-0fb3b3313d5f.png)
我在TenantSecurityWebFilter->isIgnoreUrl 方法中添加了日志。request.getRequestURI()的值不是我请求的app-api/demo/test/get url，而是 /rpc-api/infra/api-access-log/create 这个不知道为什么。
![image](https://user-images.githubusercontent.com/10906487/222305083-3d5c8510-074a-437d-8569-19090db2bedc.png)

**Comment by avoidsight** [comment]
估计是你请求接口的时候默认调了infra的请求日志接口, 但是你源接口并没有带tenant_id,infra的日志接口需要tenant_id, 这个过程是异步的, 所以对你请求接口没有影响

**Comment by guobin510** [comment]
请求的接口是这样的。
![image](https://user-images.githubusercontent.com/10906487/222383212-054afdcf-0777-43cc-b11c-8e3473a143ad.png)

**Comment by guobin510** [comment]
怎么能看出来有没有调用 infra的请求日志接口？

**Comment by avoidsight** [comment]
> 

你看看你有没有引入operatelog模块, 引入这个模块会默认给所有加了@ApiOperation的接口写操作日志,可以使用@OperateLog(enable=false)取消对目标接口的日志写入

**Comment by guobin510** [comment]
添加了，也是一样。不知道是怎么回事。

**Comment by guobin510** [comment]
![image](https://user-images.githubusercontent.com/10906487/222652478-ed98473d-90b1-4237-bdd6-2692791c1021.png)
![image](https://user-images.githubusercontent.com/10906487/222652526-450516b6-c382-4fd2-a464-3f2c0331aaff.png)

**Comment by avoidsight** [comment]
@operateLog(enable=false)

**Comment by 774649283** [comment]
> @operateLog(enable=false)

这个配置似乎只有post请求才会被忽略，get请求还是会走infra里去
