### ISSUE TITLE
发送邮件,rocketmq上的topic没绑定消费者

### ISSUE THREAD

**Issue by avoidsight** [YunaiV/yudao-cloud#83]
### 基本信息

- ruoyi-vue-pro 版本：1.7.1-snapshot
- 操作系统：macOS
- 数据库：mysql

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：rocketmq消费者和topic没有绑定

### 复现步骤

第一步，调用邮件中发送邮件的接口, rocketmq上有相应的消息,和消费者,但是并没有绑定

<img width="674" alt="image" src="https://user-images.githubusercontent.com/29603144/222350259-177df2c0-d857-4e7a-b8a4-d13931b9f1c7.png">

<img width="1485" alt="image" src="https://user-images.githubusercontent.com/29603144/222350005-199e6029-bd09-42ee-9a62-2118563c508e.png">

<img width="1374" alt="image" src="https://user-images.githubusercontent.com/29603144/222349801-5c3c168a-f2d5-40ae-8325-c5ce5e53911b.png">

配置信息
<img width="793" alt="image" src="https://user-images.githubusercontent.com/29603144/222350561-bfeac8f7-6b73-47c5-9f45-2d70e519f758.png">

**Comment by YunaiV** [comment]
已修复。
