### ISSUE TITLE
maven打包打的都是快照

### ISSUE THREAD

**Issue by IOSYuan** [YunaiV/yudao-cloud#84]
碰到问题，请在 <https://github.com/YunaiV/yudao-cloud/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：
- 操作系统：
- 数据库：

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：xxxxxx

### 复现步骤

第一步，

第二步，

第三步，

### 报错信息

带上必要的截图

**Comment by YunaiV** [comment]
是快照，符合预期哈。

**Comment by xjg2012** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，邮件已经收到，我将尽快给您回复。
