### ISSUE TITLE
【欢迎贡献】多租户工具类

### ISSUE THREAD

**Issue by machunguang** [YunaiV/yudao-cloud#85]
![image](https://user-images.githubusercontent.com/73378332/230588202-55f0ceed-575f-4c72-9417-a0c1bb409540.png)

多租户的情情况下，子线程是不是就获取不到主线程中的关于租户的一些设置，threadLocal变量是不共享的，这个TenantUtils是不是有点小问题呢，还是我理解的片面了

**Comment by YunaiV** [comment]
估计要换成阿里的 TTL ，有兴趣可以贡献下。

**Comment by YunaiV** [comment]
已经是 ttl
