### ISSUE TITLE
验证码文档的图片看不了

### ISSUE THREAD

**Issue by anuo** [YunaiV/yudao-cloud#86]
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/3096202/231954678-4fed2801-8457-41f2-9929-75fe78ef71ca.png">
对应链接 https://cloud.iocoder.cn/captcha/#_1-%E4%BA%A4%E4%BA%92%E6%B5%81%E7%A8%8B

**Comment by YunaiV** [comment]
已修复！
