### ISSUE TITLE
Unable to find instance for system-server

### ISSUE THREAD

**Issue by AsgardGod** [YunaiV/yudao-cloud#87]
碰到问题，请在 <https://github.com/YunaiV/yudao-cloud/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：最新版
- 操作系统：Windows11
- 数据库：5.7

项目启动出现问题

- 在gateway，system，infra以及前端都启动之后，浏览器登录界面出现“Unable to find instance for system-server”

但是在nacos服务列表中有system-server，不知道是什么原因

### 你猜测可能的原因

（必填）我花费了 2-4 小时自查，发现可能的原因是：xxxxxx

### 复现步骤

第一步，

第二步，

第三步，

### 报错信息

带上必要的截图
<img width="1080" alt="Snipaste_2023-04-24_18-18-27" src="https://user-images.githubusercontent.com/75120987/233968772-21f7a955-4c0a-4a91-b609-9240dafcaa74.png">

**Comment by YunaiV** [comment]
nacos 没注册上，建议看看。
