### ISSUE TITLE
【欢迎贡献】yudao项目版本号问题

### ISSUE THREAD

**Issue by tomcat-yf** [YunaiV/yudao-cloud#88]
基本信息
ruoyi-vue-pro 版本：1.7.1-snapshot
操作系统：macOS
数据库：mysql

问题
<spring.cloud.alibaba.version>2021.0.1.0</spring.cloud.alibaba.version>
使用当前版本 nacos配置的 server-addr 使用域名可以正常访问，
当版本切换为<spring.cloud.alibaba.version>2021.0.4.0</spring.cloud.alibaba.version>
会导致nacos服务连接不上

**Comment by YunaiV** [comment]
暂时没测试过高版本，有兴趣可以贡献下。

**Comment by wdkang123** [comment]
> 基本信息 ruoyi-vue-pro 版本：1.7.1-snapshot 操作系统：macOS 数据库：mysql
> 
> 问题 <spring.cloud.alibaba.version>2021.0.1.0</spring.cloud.alibaba.version> 使用当前版本 nacos配置的 server-addr 使用域名可以正常访问， 当版本切换为<spring.cloud.alibaba.version>2021.0.4.0</spring.cloud.alibaba.version> 会导致nacos服务连接不上

我本地测试的情况是：
1.在2021.0.1.0正常链接
2.在2021.0.4.0出现错误 原因是 gRPC 导致的 你的nacos(2.x版本以上)可能是没开放grpc的端口 就是你HTTP的端口+1000 比如说你HTTP服务端口是32000、那你的grpc端口就是33000 也要开放出来 就好了

**Comment by YunaiV** [comment]
> 

支持你的说法哈。
