### ISSUE TITLE
【欢迎贡献】自动生成代码完善vm模板，如果主键设置非"id"生成代码会报错，如主键为 “item_id”，建议如下完善版本

### ISSUE THREAD

**Issue by luckyhe88** [YunaiV/yudao-cloud#90]
碰到问题，请在 <https://github.com/YunaiV/yudao-cloud/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- yudao-cloud 版本：
- 操作系统：wind10/MAC
- 数据库：mysql5.7

### 你猜测可能的原因

目前VM模板默认都是按主键"id"生成，如果主键设置非"id"（如item_id）生成代码前端vue，后端java都有错误，目前我修改的vue-vben的模板；

### 复现步骤（建议按下面完善代码）

第一步，前端代码修改3个模板
    前端代码模板vm的修改  ： datats.vm , formvue.vm , index.vue.vm
        # datats.vm 文件修改成如下 72,73 行 修改成如下动态读取主键字段
        export const formSchema: FormSchema[] = [
          {
            label: '${primaryColumn.columnComment}',
            field: '${primaryColumn.javaField}',
            show: false,
            component: 'Input'
          },
       formvue.vm 文件 #data.record.id  29行 修改成如下动态读取主键字段
        if (unref(isUpdate)) {
          const res = await get${simpleClassName}(data.record.${primaryColumn.javaField})
          setFieldsValue({ ...res })
        }
        # index.vue.vm 文件 86行 record.id 修改如下，动态读取主键字段
      async function handleDelete(record: Recordable) {
        await delete${simpleClassName}(record.${primaryColumn.javaField})
        createMessage.success(t('common.delSuccessText'))
        reload()
      }

第二步： 后端代码模板修改（还是保留，生成之后用户自行修改）
        a.  DO 不需要主键处理， 删除下面3行配置
            #if (${column.primaryKey})##处理主键
            @TableId#if (${column.javaType} == 'String')(type = IdType.INPUT)#end
            #end
        b. 修改 mapper.vm 55/56 , 61/62行修改如下，获取主键的方法动态获取，不是写死getId
           #listCondition().orderByDesc(${table.className}DO::get${primaryColumn.javaField.subtring(0,1).toUpperCase()}${primaryColumn.javaField.subtring(1)}));

        c.修改 serviceImpl.vm 36，42行
          getId() 修改成动态获取主键的方法
          get${primaryColumn.javaField.subtring(0,1).toUpperCase()}${primaryColumn.javaField.subtring(1)}()

### 报错信息

目前我就截java后端一个错误，前端错误图省略
![image](https://github.com/YunaiV/yudao-cloud/assets/35294677/ea199209-6ae5-4bf7-8e34-f2b74daafb3b)

**Comment by luckyhe88** [comment]
![image](https://github.com/YunaiV/yudao-cloud/assets/35294677/42725011-4bb3-47fa-9154-ce029dba281a)

**Comment by YunaiV** [comment]
有兴趣可以 pr 下，应该 10 分钟就可以搞定。

**Comment by luckyhe88** [comment]
我可以来参与 pr ， 需要怎么配合 ？没有搞过开源的项目
















在 2023-05-29 00:09:29，"芋道源码" ***@***.***> 写道：

有兴趣可以 pr 下，应该 10 分钟就可以搞定。

**Comment by YunaiV** [comment]
> 我可以来参与 pr ， 需要怎么配合 ？没有搞过开源的项目 在 2023-05-29 00:09:29，"芋道源码" ***@***.***> 写道： 有兴趣可以 pr 下，应该 10 分钟就可以搞定。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

fork 这个仓库，然后修改实现，之后 pull request 过来，就可以啦。

**Comment by YunaiV** [comment]
暂时不考虑支持，保持 id 作为主键
