### ISSUE TITLE
能提供下项目拆分的思路吗

### ISSUE THREAD

**Issue by wudidehuangtiandi** [YunaiV/yudao-cloud#91]
### 基本信息

每个子项目单独git仓库的情况下 yushang-dependencies 要如何使用，对应不同的模块需要做删减吗。我们考虑后期自动化需要每个模块单独立项。

**Comment by YunaiV** [comment]
推送到私服 nexus 即可。

**Comment by zsm5833** [comment]
> 推送到私服 nexus 即可。

请问是不是带module字眼的可以拆分? framework跟gateway跟着脚手架?

**Comment by jinpan87** [comment]
推送nexus上去了也失败呀
