### ISSUE TITLE
common下工具类StrUtils.maxLength的疑问

### ISSUE THREAD

**Issue by wnhyang** [YunaiV/yudao-cloud#93]
### 基本信息

- ruoyi-vue-pro 版本：1.7.3-snapshot
- 操作系统：macos13
- 数据库：mysql

### 你猜测可能的原因

StrUtils.maxLength感觉没必要，Hutool的StrUtil.sub已经很完善了，而且代码中
`return StrUtil.sub(str, 0, maxLength - 3) + "..."; // -3 的原因，是该方法会补充 ... 恰好`
确实没看懂，测试了Hutool，-3并不符合要求，反而不需要

### 复现步骤

第一步，调用StrUtils.maxLength，maxLength小于str.length即可

第二步，发现-3不正确

第三步，完全可以直接调用Hutool的StrUtl.sub方法啊

### 报错信息

带上必要的截图

**Comment by YunaiV** [comment]
hutool 的，如果不到 3 个，也会拼接 ...
