### ISSUE TITLE
【欢迎贡献】swagger+knife4j 配置账号密码和enabled设为false不生效

### ISSUE THREAD

**Issue by chenhao523** [YunaiV/yudao-cloud#95]
碰到问题，请在 <https://github.com/YunaiV/yudao-cloud/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：
- 操作系统：windows
- 数据库：pgsql14

### 你猜测可能的原因

（必填）可能是版本问题

### 复现步骤

第一步，将springdoc和kfnife4j的enabled改为false,重启项目doc.html仍然可以访问

第二步，在knife4j上配置账号密码，重启项目进入doc.html并未提示输入账号密码，直接显示了文档

/
/
### 报错信息

带上必要的截图
![image](https://github.com/YunaiV/yudao-cloud/assets/43713550/fdcd2d81-e4c8-4dd8-8696-c65837c8e9aa)
![image](https://github.com/YunaiV/yudao-cloud/assets/43713550/a492fd9b-31eb-4ee1-bf06-469d93cc72aa)

**Comment by YunaiV** [comment]
确实有这个问题~
最近在忙，看看社区其他同学有没兴趣贡献下。

**Comment by insist-learning** [comment]
最新的 master 分支试了下，springdoc.api-docs.enabled 和 springdoc.swagger-ui.enabled 都是可以正常开关的
至于关闭 knife4j ,跟那个 enable 没有关系，这个是启动增强模式的，就是自定义 ui 界面的一些功能,
启动后配置了用户名和密码访问时也可以正常弹窗,这三个配置关系如下
1. springdoc.api-docs.enabled ： 关闭 api 元数据，关闭后 swagger 和 knife4j 都会失效
2. springdoc.swagger-ui.enabled，关闭后 swagger 会失效，同时 knife4j 也会失效，因为它只是个 swagger 的皮肤
3. knife4j.enabled ，关闭的是增强模式，即自定义配置是否生效
4. 如果想要让 doc.html 不可访问，可以设置 knife4j.production 为 true，默认以下资源都不能访问
![image](https://github.com/YunaiV/yudao-cloud/assets/40890438/a9d03048-56a8-4c20-a3d8-e2c957360410)
5. 如果想要修改默认规则，就自定义 ProductionSecurityFilter 这个 bean，该 bean 包含在自动配置类 Knife4jAutoConfiguration

**Comment by YunaiV** [comment]
对的，已经处理了哈。
