### ISSUE TITLE
时间控件页面上实现，但是弹窗内为输入框

### ISSUE THREAD

**Issue by fushengaaa** [YunaiV/yudao-cloud#97]
碰到问题，请在 <https://github.com/YunaiV/yudao-cloud/issues> 搜索是否存在相似的 issue。

不按照模板提交的 issue，会被系统自动删除。

### 基本信息

- ruoyi-vue-pro 版本：
- 操作系统：windows
- 数据库：

### 你猜测可能的原因

可能是vben版本问题

### 复现步骤

由代码生成器生成的页面时间控件已实现

但是弹窗内的时间控件为输入框

### 报错信息

![微信截图_20230614165251](https://github.com/YunaiV/yudao-cloud/assets/126736181/588ecbc5-2982-4f72-97f4-8fb406c9e4fb)
![微信截图_20230614165318](https://github.com/YunaiV/yudao-cloud/assets/126736181/af45b0c9-02ec-40a7-9eea-c1113dab4305)
![微信截图_20230614165642](https://github.com/YunaiV/yudao-cloud/assets/126736181/dafcc32f-f70d-4884-81e3-70f488c11e9a)

**Comment by YunaiV** [comment]
https://gitee.com/yudaocode/yudao-ui-admin-vben
辛苦提到这里哈
