### ISSUE TITLE
【欢迎贡献】springcloud tencent 版本的什么时候出来

### ISSUE THREAD

**Issue by ZhangChengJi** [YunaiV/yudao-cloud#99]
springcloud tencent 版本的什么时候出来

**Comment by YunaiV** [comment]
不确定，Q3 或者 Q4 吧~ 改动应该不多。

**Comment by YunaiV** [comment]
如果有同学有兴趣搞这块，可以私信 wangwenbin-server

**Comment by YunaiV** [comment]
综合考虑，从各方面信息看，spring cloud tencent 很难成为主流，所以暂时不会去支持。
